### ISSUE TITLE
Path Canonicalization Failed

### ISSUE THREAD

**Issue by zoom-jm** [sebastianjnuwu/ssh-action-deploy#4]
Been using this for a couple months & it's been working great ... NO issues! Today, I tried getting this working on a different server & started running into an issue. I've validated the target directory exists BEFORE running this step & it's obviously getting cleaned up but looks like it's having trouble re-creating it via the copy over SSH. 

scp: realpath //app/source: No such file
scp: upload "//app/source": path canonicalization failed
scp: failed to upload directory abcdef to //app/source

Target machine is running Ubuntu 14.04.6 LTS.

**Workflow Usage**
`      - name: Copy via SSH
        uses: sebastianjnuwu/ssh-action-deploy@v3
        with:
          IP: host
          USER: user
          KEY: key
          FOLDER: /app/source
`

**Log**
`Run sebastianjnuwu/ssh-action-deploy@v3
  with:
    IP: XXX.XX.XX.XXX
    USER: ***********
    KEY: ***
    FOLDER: /app/source
    RUN: ls -larth /app;ls -lart /app/source;
    REPO: repo/abcdef
  env:
    key_name: key_abcdef
    dir_target: /app/source
Run mkdir -p ~/.ssh/
  mkdir -p ~/.ssh/
  echo "***
  ***
  ***
  ***
  ***
  ***
  ***" > ~/.ssh/ssh.key
  chmod 600 ~/.ssh/ssh.key
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    key_name: key_abcdef
    dir_target: /app/source
Run cat >>~/.ssh/config <<END
  cat >>~/.ssh/config <<END
  Host ssh
    HostName 172.31.0.10
    User ghdeploy
    Port 22
    IdentityFile ~/.ssh/ssh.key
    StrictHostKeyChecking no
  END
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    key_name: key_abcdef
    dir_target: /app/source
Run ssh ssh rm -rf "/app/source"; 
  ssh ssh rm -rf "/app/source"; 
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    key_name: key_abcdef
    dir_target: /app/source
Run cd ..
  cd ..
  IN="repo/abcdef"
  set -- "$IN" 
  IFS="/"; declare -a Array=($*) 
  scp -r ${Array[1]} ssh://app/source
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    key_name: key_abcdef
    dir_target: /app/source
scp: realpath //app/source: No such file
scp: upload "//app/source": path canonicalization failed
scp: failed to upload directory abcdef to //app/source
Error: Process completed with exit code 1.
`

**Comment by zoom-jm** [comment]
Looks like it works manually with the '-O' flag which adds some compatibility settings. Possible to quickly add that as an option for the action?

**Comment by zoom-jm** [comment]
PR #5 created to provide a working option to address this.

**Comment by sebastianjnuwu** [comment]
@zoom-jm with your PR you already solve the problem right!? I will update to V4; thanks for your contribution ^^

**Comment by sebastianjnuwu** [comment]
Check if it is working; for some reason it did not work on my VPS

**Comment by zoom-jm** [comment]
@sebastianjnuwu Yes, that PR solved the problem on my end & I've used my fork a bunch on my end. Just tested my workflows referencing 'sebastianjnuwu/ssh-action-deploy@v4' & they continue to work. Thanks!

![CleanShot 2024-10-25 at 13 09 33@2x](https://github.com/user-attachments/assets/01db3c4a-ff91-45de-834f-6e2efae32ed6)
